### PR TITLE
BMP280 datasheet url changed

### PR DESCRIPTION
**Pull request by rvolgers**
URL didn't work, looks like they dropped the revision number from the filenames.

### CODE REVIEW

**Comment by marcan** [comment]
@whitequark is this the point where we start linking datasheets to your library instead?

**Comment by whitequark** [comment]
@marcan Almost. I'm going to make a separate repo for just the docs used in Glasgow, and add it as a submodule.

**Comment by whitequark** [comment]
That was actually the plan from the beginning, hence the relatively uniform "Reference:" format. Would need to clean it up a bit.

**Comment by whitequark** [comment]
https://github.com/whitequark/Glasgow-Archive now exists, eliminating this problem in the future.

**Pull request merged**
